const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');

(async () => {
  const records = await import(pathToFileURL(path.resolve(__dirname, '../pythonlab/learning-record.js')));
  const progress = await import(pathToFileURL(path.resolve(__dirname, '../pythonlab/progress.js')));
  let now = 0;
  let timings = {};
  let clock = records.createLearningClock(timings, () => now);
  clock.select(1); clock.setRunning(true);
  now = 1200;
  assert.equal(clock.elapsed(), 1200);
  clock.checkpoint(); clock.checkpoint();
  assert.equal(clock.elapsed(), 1200, 'multiple checkpoints must not double count');
  now += 800;
  clock.setRunning(false);
  now += 3600000;
  assert.equal(clock.elapsed(), 2000, 'hidden tabs and certificate viewing must not add time');
  clock.setRunning(true); now += 500;
  clock.select(2); clock.setRunning(true); now += 700;
  clock.select(1); clock.setRunning(true);
  assert.equal(clock.elapsed(), 2500, 'unit timing is independent');
  assert.equal(timings[2].elapsedMs, 700);
  clock.setPaused(true); now += 3000; clock.setRunning(true);
  assert.equal(clock.isRunning(), false, 'visibility change must not undo manual pause');
  assert.equal(clock.elapsed(), 2500);
  clock.setPaused(false); clock.setRunning(true); now += 500;
  clock.setRunning(false);
  timings = JSON.parse(JSON.stringify(timings));
  now += 86400000; // Next day: resume persisted time, never count time spent offline.
  clock = records.createLearningClock(timings, () => now);
  clock.select(1); clock.setRunning(true);
  assert.equal(clock.elapsed(), 3000);
  now += 1500;
  assert.equal(clock.elapsed(), 4500);
  clock.select(null); now += 1000;
  assert.equal(clock.elapsed(), 0, 'overview must not accumulate unit time');
  assert.equal(timings[1].elapsedMs, 4500);
  const damaged = { 1: { elapsedMs: -5 }, 2: { elapsedMs: Infinity }, 3: [] };
  const fixed = records.createLearningClock(damaged, () => 0);
  for (const id of [1, 2, 3]) { fixed.select(id); assert.equal(fixed.elapsed(), 0); }
  assert.equal(records.formatDuration(0), '00:00:00');
  assert.equal(records.formatDuration(3661999), '01:01:01');
  assert.equal(records.formatDuration(100 * 3600000), '100:00:00', 'hours must not wrap at midnight');
  assert.equal(records.formatDuration(NaN), '00:00:00');
  assert.equal(records.validStudent({ className: '七年一班', seat: '08', name: '測試同學' }), true);
  assert.deepEqual(records.normalizeStudent({ className: ' 七年一班 ', seat: ' 08 ', name: ' 小安 ' }), { className: '七年一班', seat: '08', name: '小安' });
  for (const seat of ['', '0', '000', '-1', '1.5', 'abc', '１', '1000']) assert.equal(records.validStudent({ className: '701', name: '小安', seat }), false);
  assert.equal(records.validStudent({ className: ' ', seat: '1', name: '小安' }), false);
  assert.equal(records.validStudent({ className: '701', seat: '1', name: ' ' }), false);
  assert.equal(records.certificateRecord(undefined), null);
  let completed = progress.awardTier(undefined, 1, { code: 'one', verifiedAt: 100, elapsedMs: 3000 });
  assert.deepEqual(records.certificateRecord(completed), { stars: 1, achievedAt: 100, elapsedMs: 3000, partial: false });
  now += 4000000;
  assert.equal(records.certificateRecord(completed).elapsedMs, 3000, 'certificate time must be frozen at achievement');
  completed = progress.awardTier(completed, 2, { code: 'two', verifiedAt: 200, elapsedMs: 5000 });
  completed = progress.awardTier(completed, 1, { code: 'one again', verifiedAt: 300, elapsedMs: 6000 });
  assert.deepEqual(records.certificateRecord(completed), { stars: 2, achievedAt: 200, elapsedMs: 5000, partial: false }, 'rechecking a lower tier cannot replace the highest certificate');
  assert.equal(progress.canAttemptTier(completed, 3), true, 'receiving a certificate must not lock further challenges');
  completed = progress.awardTier(completed, 3, { code: 'three', verifiedAt: 400, elapsedMs: 7000 });
  assert.equal(records.certificateRecord(completed).stars, 3);
  const legacy = progress.migrateCompletion({ 1: { code: 'legacy', verifiedAt: 50 } });
  assert.equal(records.certificateRecord(legacy[1]).elapsedMs, null, 'old records must not fabricate learning time');
  const upgraded = progress.awardTier(legacy[1], 2, { code: 'new', verifiedAt: 500, elapsedMs: 1000, timingPartial: true });
  assert.equal(records.certificateRecord(upgraded).partial, true);
  console.log('Learning records: independent timing, pause/resume, offline/next-day persistence, frozen and upgraded certificates, legacy timing, identity validation passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
