const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const root = path.resolve(__dirname, '..');
(async () => {
  const { characterInfo, codePointInfo, parseCodePoint } = await import(pathToFileURL(path.join(root, 'pythonlab/encoding.js')));
  const { extensions } = await import(pathToFileURL(path.join(root, 'pythonlab/helper-data.js')));
  assert.deepEqual(characterInfo('A').bytes, [65]);
  assert.equal(characterInfo('A').hex, '0x41');
  assert.equal(characterInfo('A').binary, '0b1000001');
  assert.equal(characterInfo('A').ascii, true);
  assert.deepEqual(characterInfo('中').bytes, [228, 184, 173]);
  assert.equal(characterInfo('中').decimal, 20013);
  assert.equal(characterInfo('中').ascii, false);
  assert.deepEqual(characterInfo('😀').bytes, [240, 159, 152, 128]);
  assert.equal(characterInfo('😀').decimal, 128512);
  assert.equal(characterInfo(' ').decimal, 32);
  assert.equal(codePointInfo(0).control, true);
  assert.equal(codePointInfo(0x10ffff).decimal, 1114111);
  for (const input of ['65', '0x41', '0b1000001', ' 65 ']) assert.equal(parseCodePoint(input).character, 'A');
  for (const input of ['', 'AB', 'e\u0301']) assert.throws(() => characterInfo(input));
  for (const input of ['', '3.5', '-1', '0xZZ', '0b102', '1114112', '55296', 'Infinity']) assert.throws(() => parseCodePoint(input));
  for (const value of [0, 127, 128, 20013, 128512, 1114111]) assert.equal(characterInfo(codePointInfo(value).character).decimal, value);
  const examples = extensions.filter(entry => entry.output);
  const driver = 'import json, sys, io, contextlib\nfor item in json.load(sys.stdin):\n    output = io.StringIO()\n    with contextlib.redirect_stdout(output):\n        exec(item["code"], {})\n    assert output.getvalue().strip() == item["output"], item["name"]\n';
  execFileSync('python', ['-X', 'utf8', '-c', driver], { cwd: root, input: JSON.stringify(examples), encoding: 'utf8' });
  console.log('Reference helper: ASCII, Unicode, UTF-8, emoji, number bases, invalid inputs and extension examples passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
